### ISSUE TITLE
下载报错

### ISSUE THREAD

**Issue by L134139** [root-wang/TikTokDownloadVideo#1]
go: downloading github.com/spf13/viper v1.15.0
main.go:20:2: github.com/spf13/viper@v1.15.0: Get "https://proxy.golang.org/github.com/spf13/viper/@v/v1.15.0.zip": dial tcp 172.217.160.81:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by root-wang** [comment]
如果您使用的 Go 版本是 1.13 及以上 （推荐）
	go env -w GO111MODULE=on
	go env -w GOPROXY=https://goproxy.cn,direct

**Comment by L134139** [comment]
生成的tiktok.exe，运行没有反应

**Comment by L134139** [comment]
是不是国外版的抖音不能下载？

**Comment by root-wang** [comment]
> 生成的tiktok.exe，运行没有反应

生成可执行文件不是最新的版本无法使用

**Comment by root-wang** [comment]
> 是不是国外版的抖音不能下载？

本人在国内无法获取国际版抖音API
